import { FC, ReactNode } from 'react';

import './globals.css';
import { Inter } from 'next/font/google';

import AuthProvider from '~/app/context/AuthProvider';
import Navbar from '~/components/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Props = {
  children: ReactNode;
};

const RootLayout: FC<Props> = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Navbar />

          <main className="flex min-h-screen items-start justify-center p-6">{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
};

export default RootLayout;
